### PR TITLE
Creating a jupyter-book

### PR DESCRIPTION
**Pull request by suppathak**
Forking a gh-pages branch to aicoe repo.

### CODE REVIEW

**Review by chauhankaranraj — CHANGES_REQUESTED** [review]
- Do the `.jupyter` and `reports` directories have any purpose here? If not can they be removed?
- jupyterbook usually creates `.nojekyll` and `.buildinfo` files as well, were those not generated for this project? If they were, can you pls add them?

**Comment by suppathak** [comment]
> * Do the `.jupyter` and `reports` directories have any purpose here? If not can they be removed?
> * jupyterbook usually creates `.nojekyll` and `.buildinfo` files as well, were those not generated for this project? If they were, can you pls add them?

@chauhankaranraj , Thanks for the feedback. I tried to address the issue. I deleted `.jupyter` and `reports`, and added `.nojekyll and .buildinfo` file in the branch.

**Comment by chauhankaranraj** [comment]
> @chauhankaranraj , Thanks for the feedback. I tried to address the issue. I deleted `.jupyter` and `reports`, and added `.nojekyll and .buildinfo` file in the branch.

Great, thanks! Could you please squash commits and it can be merged?

**Review by chauhankaranraj — APPROVED** [review]
/approve

**Pull request merged**
